-
  name: 'FlowQuery'
  uriPattern: 'query'
  defaults:
    '@package':    'PackageFactory.FlowQueryAPI'
    '@controller': 'FlowQuery'
    '@action':     'query'
    '@format':     'json'
  appendExceedingArguments: TRUE
  httpMethods: ['POST']
